### ISSUE TITLE
BLS not supported on redhat 7

### ISSUE THREAD

**Issue by bskou57** [snapshotmanager/boom-boot#42]
Hi

grub BLS is not supported on redhat 7

Can you please advise on we need to use/configure instead ?

Thanks for your support

**Comment by bmr-cymru** [comment]
RHEL7 only supports BLS in limited circumstances: for x86_64 hosts using BIOS boot. It was decided to not enable it for UEFI systems, see the following bugzilla:

https://bugzilla.redhat.com/show_bug.cgi?id=1685223

For UEFI firmware or alternate architectures RHEL8 or later is required.

**Comment by birb57** [comment]
Hello

So we do not have solution with rhel 7 under EFI boot ?

Thanks

**Comment by bmr-cymru** [comment]
No: unfortunately the maintainers of `grub2` for RHEL7 chose not to enable BLS for EFI builds.
